### ISSUE TITLE
[Feat] 이상형 정보 입력 UI 구현

### ISSUE THREAD

**Issue by kms0233** [Festimate/Festimate-iOS#10]
## 🛠 Issue

이상형 정보 입력 UI 구현 예정
## 📝 To-do

- [ ] 이상형 정보 입력 UI
- [ ] 이상형 얼굴상 입력 UI 
- [ ] 화면 전환 연결
