### ISSUE TITLE
[Feat] 매칭하러 가기 UI 구현

### ISSUE THREAD

**Issue by kms0233** [Festimate/Festimate-iOS#7]
## 🛠 Issue

매칭하러 가기 UI 및 로직 구현 예정입니닷
## 📝 To-do

- [x] 가능 시간대 UI
- [x] 착장 정보
- [x] 계좌 번호 안내 UI
- [x] 계좌 번호 복사 시 팝업창 UI
